<?php

return [
    'default_vendor' => 'mikrotik',
    'vendors' => [
        'mikrotik' => [
            'display_name' => 'MikroTik',
            'driver' => 'mikrotik',
            'capability_profile' => 'ros7',
            'aliases' => ['routerboard', 'mtik'],
            'model_patterns' => [
                'mikrotik',
                'routerboard',
                'hap*',
                'crs*',
                'rb*',
                'sxt*',
                'lhg*',
                'ccr*',
                'map*',
            ],
            'supports' => [
                'pppoe' => true,
                'hotspot' => true,
                'vlan' => true,
                'rest_api' => true,
                'ssh' => true,
                'snmp' => true,
            ],
        ],
        'cisco' => [
            'display_name' => 'Cisco',
            'driver' => 'cisco',
            'capability_profile' => 'cisco_ios',
            'aliases' => ['isr', 'asr', 'catalyst'],
            'model_patterns' => [
                'cisco',
                'isr*',
                'asr*',
                'catalyst*',
                'c[0-9][0-9][0-9][0-9]*',
            ],
            'supports' => [
                'pppoe' => false,
                'hotspot' => false,
                'vlan' => true,
                'rest_api' => false,
                'ssh' => true,
                'snmp' => true,
            ],
        ],
        'ubiquiti' => [
            'display_name' => 'Ubiquiti',
            'driver' => 'ubiquiti',
            'capability_profile' => 'ubiquiti_edgeos',
            'aliases' => ['ubnt', 'edgerouter', 'edgeswitch', 'unifi'],
            'model_patterns' => [
                'ubiquiti',
                'ubnt',
                'edgeswitch*',
                'edgerouter*',
                'unifi*',
            ],
            'supports' => [
                'pppoe' => true,
                'hotspot' => true,
                'vlan' => true,
                'rest_api' => false,
                'ssh' => true,
                'snmp' => true,
            ],
        ],
        'tplink' => [
            'display_name' => 'TP-Link',
            'driver' => 'tplink',
            'capability_profile' => 'tplink_omada',
            'aliases' => ['tp-link', 'omada', 'tl'],
            'model_patterns' => [
                'tp-link',
                'tplink',
                'omada*',
                'tl-*',
            ],
            'supports' => [
                'pppoe' => true,
                'hotspot' => true,
                'vlan' => true,
                'rest_api' => true,
                'ssh' => true,
                'snmp' => true,
            ],
        ],
        'juniper' => [
            'display_name' => 'Juniper',
            'driver' => 'juniper',
            'capability_profile' => 'juniper_junos',
            'aliases' => ['srx', 'mx', 'ex'],
            'model_patterns' => [
                'juniper',
                'srx*',
                'mx*',
                'ex*',
            ],
            'supports' => [
                'pppoe' => true,
                'hotspot' => false,
                'vlan' => true,
                'rest_api' => false,
                'ssh' => true,
                'snmp' => true,
            ],
        ],
    ],
];
