<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Traits\HasUuid;
use App\Traits\BelongsToTenant;
use App\Models\Scopes\TenantScope;

class Package extends Model
{
    /** @use HasFactory<\Database\Factories\PackageFactory> */
    use HasFactory, HasUuid, BelongsToTenant;

    /**
     * The "booted" method of the model.
     */
    protected static function booted(): void
    {
        static::addGlobalScope(new TenantScope());
    }

    protected $fillable = [
        'tenant_id',
        'type',
        'name',
        'description',
        'duration',
        'upload_speed',
        'download_speed',
        'speed',
        'price',
        'devices',
        'data_limit',
        'validity',
        'enable_burst',
        'enable_schedule',
        'scheduled_activation_time',
        'scheduled_deactivation_time',
        'hide_from_client',
        'is_global',
        'status',
        'is_active',
        'is_public',
        'users_count',
    ];

    protected $casts = [
        'id' => 'string',
        'price' => 'float',
        'devices' => 'integer',
        'users_count' => 'integer',
        'enable_burst' => 'boolean',
        'enable_schedule' => 'boolean',
        'hide_from_client' => 'boolean',
        'is_global' => 'boolean',
        'is_active' => 'boolean',
        'is_public' => 'boolean',
        'scheduled_activation_time' => 'datetime',
        'scheduled_deactivation_time' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    /**
     * Routers assigned to this package (many-to-many)
     */
    public function routers()
    {
        return $this->belongsToMany(Router::class, 'package_router')
            ->withTimestamps();
    }

    /**
     * Payments made for this package
     */
    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

    /**
     * User sessions using this package
     */
    public function userSessions()
    {
        return $this->hasMany(UserSession::class);
    }

    /**
     * Check if package is available for a specific router
     */
    public function isAvailableForRouter($routerId): bool
    {
        // Global packages are available for all routers
        if ($this->is_global) {
            return true;
        }

        // Check if package is specifically assigned to this router
        return $this->routers()->where('router_id', $routerId)->exists();
    }

    /**
     * Get revenue generated by this package
     */
    public function getRevenue($routerId = null)
    {
        $query = $this->payments()->where('status', 'completed');
        
        if ($routerId) {
            $query->where('router_id', $routerId);
        }
        
        return $query->sum('amount');
    }
}