<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ServiceVlan extends Model
{
    use HasFactory, HasUuids;

    protected $fillable = [
        'router_service_id',
        'vlan_id',
        'vlan_name',
        'parent_interface',
        'service_type',
        'auto_generated',
    ];

    protected $casts = [
        'vlan_id' => 'integer',
        'auto_generated' => 'boolean',
    ];

    public function routerService(): BelongsTo
    {
        return $this->belongsTo(RouterService::class);
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('auto_generated', true);
    }

    public function scopeForService($query, string $serviceType)
    {
        return $query->where('service_type', $serviceType);
    }

    public function getVlanInterfaceName(): string
    {
        return $this->vlan_name ?? "vlan-{$this->service_type}-{$this->vlan_id}";
    }
}
