[program:laravel-queue-broadcasts]
command=/usr/local/bin/php artisan queue:work --queue=broadcasts --sleep=1 --tries=3 --timeout=30 --max-time=3600 --memory=128 --backoff=2,5,10
directory=/var/www/html
environment=LARAVEL_ENV="production"
autostart=true
autorestart=true
startretries=3
startsecs=5
stopwaitsecs=30
stopsignal=TERM
priority=3
user=www-data
numprocs=2
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[program:laravel-queue-emails]
command=/usr/local/bin/php artisan queue:work --queue=emails --sleep=1 --tries=3 --timeout=120 --max-time=3600 --memory=128 --backoff=5,15,30
directory=/var/www/html
environment=LARAVEL_ENV="production"
autostart=true
autorestart=true
startretries=3
startsecs=5
stopwaitsecs=60
stopsignal=TERM
priority=3
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[program:laravel-queue-notifications]
command=/usr/local/bin/php artisan queue:work --queue=notifications --sleep=5 --tries=3 --timeout=60 --max-time=3600 --memory=128 --backoff=5,15,30
directory=/var/www/html
environment=LARAVEL_ENV="production"
autostart=true
autorestart=true
startretries=3
startsecs=5
stopwaitsecs=60
stopsignal=TERM
priority=20
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[group:laravel-queues-realtime]
programs=laravel-queue-broadcasts,laravel-queue-emails,laravel-queue-notifications
priority=999
