[program:laravel-queue-dashboard]
command=/usr/local/bin/php artisan queue:work --queue=dashboard --sleep=3 --tries=3 --timeout=120 --max-time=3600 --memory=128 --backoff=5,15,30
directory=/var/www/html
environment=LARAVEL_ENV="production"
autostart=true
autorestart=true
startretries=3
startsecs=5
stopwaitsecs=60
stopsignal=TERM
priority=15
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=false
stdout_logfile=/var/www/html/storage/logs/dashboard-queue.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=7
stderr_logfile=/var/www/html/storage/logs/dashboard-queue-error.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=7
stopasgroup=true
killasgroup=true

[program:laravel-queue-metrics]
command=/usr/local/bin/php artisan queue:work --queue=metrics --sleep=3 --tries=3 --timeout=120 --max-time=3600 --memory=256 --backoff=5,15,30
directory=/var/www/html
environment=LARAVEL_ENV="production"
autostart=true
autorestart=true
startretries=3
startsecs=5
stopwaitsecs=60
stopsignal=TERM
priority=10
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=false
stdout_logfile=/var/www/html/storage/logs/metrics-queue.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=7
stderr_logfile=/var/www/html/storage/logs/metrics-queue-error.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=7
stopasgroup=true
killasgroup=true

[group:laravel-queues-metrics]
programs=laravel-queue-dashboard,laravel-queue-metrics
priority=999
