<?php

namespace Database\Seeders;

use App\Models\Tenant;
use App\Models\User;
use App\Services\TenantSchemaManager;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class SystemLandlordSeeder extends Seeder
{
    /**
     * Seed the system landlord tenant and user.
     *
     * The landlord tenant is a special tenant that manages the SaaS platform.
     * It has system-level access to aggregate metrics and billing controls.
     *
     * Schema is auto-created by Tenant::created boot hook via TenantMigrationManager::setupTenantSchema().
     * No DB::beginTransaction — DDL (CREATE SCHEMA, GRANT) cannot be inside a transaction.
     */
    public function run(): void
    {
        $this->command->info('Creating System Landlord tenant and user...');

        // Create landlord tenant (schema auto-created by Tenant::created hook)
        $tenant = $this->createLandlordTenant();

        // Create landlord admin user
        $user = $this->createLandlordUser($tenant);

        $this->command->info('✅ System Landlord created successfully!');
        $this->command->warn('');
        $this->command->warn('⚠️  IMPORTANT: Change the default landlord password immediately!');
        $this->command->warn('    Email: ' . $user->email);
        $this->command->warn('    Default Password: ' . config('saas.landlord.default_admin_password', 'Landlord@123!'));
        $this->command->warn('');
    }

    /**
     * Create the landlord tenant
     */
    private function createLandlordTenant(): Tenant
    {
        $slug = config('saas.landlord.tenant_slug', 'system-landlord');
        $name = config('saas.landlord.tenant_name', 'System Landlord');

        // Check if landlord tenant already exists
        $existingTenant = Tenant::where('slug', $slug)->first();

        if ($existingTenant) {
            $this->command->info('Landlord tenant already exists, updating...');
            $existingTenant->update([
                'name' => $name,
                'is_landlord' => true,
                'is_default' => true,
                'is_active' => true,
                'subscription_status' => 'active',
                'subscription_ends_at' => null, // Landlord never expires
            ]);

            // Ensure schema is created if it doesn't exist
            if (!$existingTenant->schema_created) {
                $this->command->info('Setting up schema for existing landlord tenant...');
                $this->setupTenantSchema($existingTenant);
            }

            return $existingTenant;
        }

        // Create new landlord tenant
        // schema_name auto-generated by Tenant::boot() creating() hook
        // schema auto-created by Tenant::boot() created() hook via TenantMigrationManager::setupTenantSchema()
        $tenant = Tenant::create([
            'name' => $name,
            'slug' => $slug,
            'email' => config('saas.landlord.default_admin_email', 'landlord@wificore.local'),
            'is_active' => true,
            'is_landlord' => true,
            'is_default' => true,
            'subscription_status' => 'active',
            'subscription_ends_at' => null, // Landlord never expires
            'settings' => [
                'is_system_tenant' => true,
                'billing_enabled' => true,
            ],
        ]);

        $this->command->info("Created landlord tenant: {$tenant->name} (ID: {$tenant->id})");
        $this->command->info("   Schema: {$tenant->schema_name}");

        // Safety net: if Tenant::created hook didn't create schema, do it manually
        if (!$tenant->schema_created) {
            $this->setupTenantSchema($tenant);
        }

        return $tenant;
    }

    /**
     * Set up tenant schema and run migrations (safety net for existing tenants)
     */
    private function setupTenantSchema(Tenant $tenant): void
    {
        try {
            $this->command->info('Setting up tenant schema: ' . $tenant->schema_name);

            $schemaManager = app(TenantSchemaManager::class);
            $schemaManager->createSchema($tenant);

            $this->command->info('✅ Tenant schema created: ' . $tenant->schema_name);
        } catch (\Exception $e) {
            $this->command->error('Failed to create tenant schema: ' . $e->getMessage());
            Log::error('SystemLandlordSeeder schema setup failed', [
                'tenant_id' => $tenant->id,
                'schema_name' => $tenant->schema_name,
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Create the landlord admin user
     */
    private function createLandlordUser(Tenant $tenant): User
    {
        $email = config('saas.landlord.default_admin_email', 'landlord@wificore.local');
        $password = config('saas.landlord.default_admin_password', 'Landlord@123!');

        // Check if landlord user already exists
        $existingUser = User::withoutTenantScope()->where('email', $email)->first();

        if ($existingUser) {
            $this->command->info('Landlord user already exists, updating role...');
            $existingUser->update([
                'role' => User::ROLE_SYSTEM_ADMIN,
                'tenant_id' => null, // System admin has no tenant
                'is_active' => true,
            ]);
            return $existingUser;
        }

        // Create new landlord user
        // Use withoutEvents to avoid BelongsToTenant::creating() assigning a default tenant_id.
        $user = User::withoutEvents(function () use ($email, $password) {
            return User::withoutTenantScope()->create([
                'id' => Str::uuid(),
                'name' => 'System Landlord',
                'username' => 'landlord',
                'email' => $email,
                'password' => Hash::make($password),
                'role' => User::ROLE_SYSTEM_ADMIN,
                'tenant_id' => null, // System admin has no tenant (can access all)
                'is_active' => true,
                'email_verified_at' => now(),
                'account_number' => 'SYS-LANDLORD-001',
            ]);
        });

        $this->command->info("Created landlord user: {$user->email} (ID: {$user->id})");

        // Add to RADIUS for authentication
        $this->addToRadius($user, $password);

        return $user;
    }

    /**
     * Add landlord user to RADIUS
     */
    private function addToRadius(User $user, string $password): void
    {
        try {
            // Add to radcheck table for authentication (use username, not email)
            DB::table('radcheck')->updateOrInsert(
                ['username' => $user->username, 'attribute' => 'Cleartext-Password'],
                [
                    'op' => ':=',
                    'value' => $password,
                ]
            );

            // Avoid Query Builder updateOrInsert here because PostgreSQL can coerce
            // booleans to integer literals in generated SQL for updates.
            DB::statement(
                'INSERT INTO public.radius_user_schema_mapping (username, pppoe_user_id, schema_name, tenant_id, user_role, is_active, created_at, updated_at)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                 ON CONFLICT (username) DO UPDATE SET
                    pppoe_user_id = EXCLUDED.pppoe_user_id,
                    schema_name = EXCLUDED.schema_name,
                    tenant_id = EXCLUDED.tenant_id,
                    user_role = EXCLUDED.user_role,
                    is_active = EXCLUDED.is_active,
                    updated_at = EXCLUDED.updated_at',
                [
                    $user->username,
                    null,
                    'public',
                    null,
                    User::ROLE_SYSTEM_ADMIN,
                    true,
                    now(),
                    now(),
                ]
            );

            $this->command->info('Added landlord user to RADIUS');

        } catch (\Exception $e) {
            $this->command->warn('Could not add landlord to RADIUS: ' . $e->getMessage());
            Log::warning('Failed to add landlord to RADIUS', [
                'error' => $e->getMessage(),
            ]);
        }
    }
}
