    public function generateConfigs(Router $router, array $data): array
    {
        // Extract data for the script generation
        $interfaceAssignments = $data['interface_assignments'] ?? [];
        $interfaceServices = $data['interface_services'] ?? [];
        $configurations = $data['configurations'] ?? [];

        $serviceScript = $this->generateServiceScript($interfaceAssignments, $interfaceServices, $configurations, $router->id, $data);

        return [
            'service_script' => $serviceScript,
        ];
    }

    private function generateServiceScript(array $interfaceAssignments, array $interfaceServices, array $configurations, int $routerId, array $data): string
    {
        $script = [
            '# Generated by Traidnet Solution LTD - Dynamic Config for Router ID: ' . $routerId,
            '# Clear existing hotspot and related configurations to ensure a clean slate',
            '/ip hotspot remove [find]',
            '/ip hotspot profile remove [find]',
            '/ip hotspot user profile remove [find]',
            '/ip pool remove [find name~"hotspot"]',
            '/ip dhcp-server remove [find name~"hotspot"]',
            '/interface bridge remove [find name~"hotspot"]',
            '',
            '# Basic network organization',
            '/interface list',
            'add name=LAN',
            'add name=WAN',
            '/interface list member',
        ];

        $hotspotIfaces = array_values(array_filter(
            $interfaceAssignments,
            fn($iface) => isset($interfaceServices[$iface]) && $interfaceServices[$iface] === 'hotspot'
        ));

        $pppoeIfaces = array_values(array_filter(
            $interfaceAssignments,
            fn($iface) => isset($interfaceServices[$iface]) && $interfaceServices[$iface] === 'pppoe'
        ));

        // Determine WAN interfaces (not assigned to hotspot or PPPoE, excluding ether1 and ether2)
        $wanIfaces = array_diff($interfaceAssignments, array_merge($hotspotIfaces, $pppoeIfaces));
        $wanIfaces = array_filter($wanIfaces, fn($iface) => !in_array($iface, ['ether1', 'ether2']));
        if (empty($wanIfaces)) {
            Log::warning('No valid WAN interfaces assigned for router ' . $routerId);
        }

        foreach ($wanIfaces as $iface) {
            $script[] = "add list=WAN interface=$iface";
        }
        $script[] = '';

        if (!empty($hotspotIfaces)) {
            $bridge = $data['hotspot_bridge_name'] ?? "br-hotspot-$routerId";
            $script[] = '# Hotspot Bridge Setup';
            $script[] = "/interface bridge add name=$bridge comment=\"Hotspot Bridge\"";
            foreach ($hotspotIfaces as $iface) {
                $script[] = "/interface bridge port add bridge=$bridge interface=$iface";
            }
            $script[] = "/interface list member add list=LAN interface=$bridge";
            $script[] = '';

            $first = $hotspotIfaces[0];
            $ipPool = $this->validateIpPool($configurations[$first]['ip_pool'] ?? '192.168.88.10-192.168.88.254');
            $network = $this->getNetworkFromPool($ipPool);
            $gateway = $this->getGatewayFromNetwork($network);
            $rateLimit = $data['hotspot_rate_limit'] ?? '5M/5M';

            $script[] = '# Hotspot IP Configuration';
            $script[] = "/ip pool add name=pool-hotspot ranges=$ipPool";
            $script[] = "/ip address add address=$gateway/24 interface=$bridge comment=\"Hotspot Gateway\"";
            $script[] = '/ip dhcp-server';
            $script[] = "add name=dhcp-hotspot interface=$bridge address-pool=pool-hotspot lease-time=1h disabled=no";
            $dnsServers = $data['dns_servers'] ?? '8.8.8.8,8.8.4.4,1.1.1.1';
            $script[] = "/ip dhcp-server network add address=$network gateway=$gateway dns-server=$dnsServers";
            $script[] = '';

            $script[] = '# Hotspot Server and Profiles';
            $hotspotProfile = "profile-hotspot-$routerId";
            $script[] = '/ip hotspot profile';
            $script[] = "add name=$hotspotProfile hotspot-address=$gateway dns-name=hotspot.local login-by=http-chap,mac,http-pap,mac-cookie http-cookie-lifetime=8h session-timeout=8h idle-timeout=15m html-directory=hotspot keepalive-timeout=5m";
            $script[] = '/ip hotspot user profile';
            $script[] = "add name=default rate-limit=$rateLimit session-timeout=8h idle-timeout=15m";
            $script[] = '/ip hotspot';
            $script[] = "add name=server-hotspot interface=$bridge address-pool=pool-hotspot profile=$hotspotProfile disabled=no";
            $script[] = '';

            $script[] = '# Walled Garden for Captive Portal';
            $script[] = '/ip hotspot walled-garden';
            $script[] = 'add dst-host=hotspot.traidnet.co.ke action=allow comment="Allow portal access"';
            $script[] = 'add dst-host=*.traidnet.co.ke action=allow comment="Allow portal subdomains"';
            $script[] = 'add dst-host=8.8.8.8 action=allow comment="Allow DNS"';
            $script[] = 'add dst-host=8.8.4.4 action=allow comment="Allow DNS"';
            $script[] = 'add dst-host=1.1.1.1 action=allow comment="Allow DNS"';
            $script[] = '';

            $loginHtml = $this->generateSecureLoginPage($gateway);
            $logoutHtml = $this->generateSecureLogoutPage();
            $script = array_merge($script, $this->mikrotikEnsureDir('hotspot'));
            $script = array_merge($script, $this->mikrotikWriteFile('hotspot/login.html', $loginHtml));
            $script = array_merge($script, $this->mikrotikWriteFile('hotspot/logout.html', $logoutHtml));
        }

        if (!empty($pppoeIfaces)) {
            $authMethods = $data['pppoe_auth_methods'] ?? 'chap,mschap2';
            $script[] = '# PPPoE Configuration';
            foreach ($pppoeIfaces as $iface) {
                $ipPool = $this->validateIpPool($configurations[$iface]['ip_pool'] ?? $this->generateRandomPool('10.0.0.0'));
                $network = $this->getNetworkFromPool($ipPool);
                $gateway = $this->getGatewayFromNetwork($network);
                $serviceName = $configurations[$iface]['pppoe_service'] ?? "pppoe-$iface";

                $script[] = "# PPPoE for interface $iface";
                $script[] = "/ip pool add name=pool-pppoe-$iface ranges=$ipPool";
                $script[] = "/ip address add address=$gateway/24 interface=$iface comment=\"PPPoE Gateway\"";
                $script[] = "/ppp profile add name=profile-pppoe-$iface local-address=$gateway remote-address=pool-pppoe-$iface";
                $script[] = "/interface pppoe-server server add service=$serviceName interface=$iface default-profile=profile-pppoe-$iface authentication=$authMethods one-session-per-host=yes disabled=no";
                $script[] = "/interface list member add list=LAN interface=$iface";
            }
            $script[] = '';
        }

        $script[] = '# Production Firewall Rules';
        $script[] = '/ip firewall filter';
        $script[] = 'add chain=input action=accept connection-state=established,related comment="Allow established/related connections"';
        $script[] = 'add chain=input action=drop connection-state=invalid comment="Drop invalid connections"';
        $script[] = 'add chain=input action=accept protocol=icmp comment="Allow ICMP (ping)"';
        $script[] = 'add chain=input action=accept in-interface-list=LAN comment="Allow access from LAN"';
        $script[] = 'add chain=input action=accept protocol=tcp dst-port=22 in-interface=ether1 comment="Allow SSH from management"';
        $script[] = 'add chain=input action=drop comment="Drop all other input traffic"';
        $script[] = 'add chain=forward action=accept connection-state=established,related comment="Allow established/related forwarding"';
        $script[] = 'add chain=forward action=drop connection-state=invalid comment="Drop invalid forward traffic"';
        $script[] = 'add chain=forward action=accept in-interface-list=LAN out-interface-list=WAN comment="Allow LAN to access WAN"';
        $script[] = 'add chain=forward action=drop comment="Drop all other forward traffic"';
        $script[] = '';

        $script[] = '# NAT Masquerade';
        $script[] = '/ip firewall nat';
        $script[] = 'add chain=srcnat action=masquerade out-interface-list=WAN comment="Masquerade LAN traffic to WAN"';
        $script[] = '';

        $script[] = '# System Logging and DNS';
        $dnsServers = $data['dns_servers'] ?? '8.8.8.8,8.8.4.4,1.1.1.1';
        $script[] = "/ip dns set allow-remote-requests=yes servers=$dnsServers";
        $script[] = '/system logging';
        $script[] = 'add topics=hotspot,info action=memory';
        $script[] = 'add topics=firewall,info action=memory';
        $script[] = 'add topics=pppoe,info action=memory';

        return implode("\n", $script);
    }
