package ssh

import (
	"strings"
	"testing"
)

// TestExtractDoBlockEscapedQuotes tests extractDoBlock with the exact on-error
// format generated by ZeroConfigPPPoEGenerator, which uses \\\" sequences.
func TestExtractDoBlockEscapedQuotes(t *testing.T) {
	// This is what PHP generates and what the Go binary receives over the API:
	line := `:do { /ppp profile set [/ppp profile find name="pppoe-prof-af80c0db"] interface-list="PA-af80c0db" } on-error={ :error "PPPoE-af80c0db: FATAL - Failed to set profile interface-list" }`
	innerCmd, _, isDoBlock := extractDoBlock(line)
	if !isDoBlock {
		t.Fatalf("extractDoBlock returned isDoBlock=false")
	}
	want := `/ppp profile set [/ppp profile find name="pppoe-prof-af80c0db"] interface-list="PA-af80c0db"`
	if innerCmd != want {
		t.Errorf("innerCmd=\n%q\nwant:\n%q", innerCmd, want)
	}
}

// TestFullPipeline tests the exact script lines that are failing in production.
// These are extracted from ZeroConfigPPPoEGenerator output and match what
// executeScript() processes after extractDoBlock().
func TestFullPipeline(t *testing.T) {
	lines := []struct {
		scriptLine  string
		wantFindMut bool
		wantFilters []string
		wantParams  []string
		wantEndpt   string
	}{
		{
			scriptLine:  `:do { /ppp profile set [/ppp profile find name="pppoe-prof-af80c0db"] interface-list="PA-af80c0db" } on-error={ :error "PPPoE-af80c0db: FATAL - Failed to set profile interface-list" }`,
			wantFindMut: true,
			wantFilters: []string{"?name=pppoe-prof-af80c0db"},
			wantParams:  []string{"interface-list=PA-af80c0db"},
			wantEndpt:   "/ppp/profile/set",
		},
		{
			scriptLine:  `:do { /ppp profile set [/ppp profile find name="pppoe-prof-af80c0db"] change-tcp-mss=yes use-compression=no only-one=yes } on-error={ :error "PPPoE-af80c0db: FATAL - Failed to apply PPP settings" }`,
			wantFindMut: true,
			wantFilters: []string{"?name=pppoe-prof-af80c0db"},
			wantParams:  []string{"change-tcp-mss=yes", "use-compression=no", "only-one=yes"},
			wantEndpt:   "/ppp/profile/set",
		},
		{
			scriptLine:  `:do { /ppp profile set [/ppp profile find name="pppoe-prof-af80c0db"] rate-limit="" } on-error={ :error "PPPoE-af80c0db: FATAL - profile rate-limit set failed" }`,
			wantFindMut: true,
			wantFilters: []string{"?name=pppoe-prof-af80c0db"},
			wantParams:  []string{"rate-limit="},
			wantEndpt:   "/ppp/profile/set",
		},
		// Context-relative [find name=...] without path prefix (RouterOS script syntax)
		{
			scriptLine:  `:do { /interface ethernet set [find name="ether1"] disable-running-check=no } on-error={}`,
			wantFindMut: true,
			wantFilters: []string{"?name=ether1"},
			wantParams:  []string{"disable-running-check=no"},
			wantEndpt:   "/interface/ethernet/set",
		},
		{
			scriptLine:  `:do { /ip firewall filter remove [find comment~"PPPoE-test"] } on-error={}`,
			wantFindMut: true,
			wantFilters: []string{"?comment~=PPPoE-test"},
			wantParams:  []string{},
			wantEndpt:   "/ip/firewall/filter/remove",
		},
	}

	for _, tt := range lines {
		t.Run(tt.scriptLine[:60], func(t *testing.T) {
			innerCmd, _, isDoBlock := extractDoBlock(tt.scriptLine)
			if !isDoBlock {
				t.Fatalf("extractDoBlock returned isDoBlock=false for: %s", tt.scriptLine)
			}
			t.Logf("innerCmd: %q", innerCmd)

			tokens := splitRouterOSCommand(innerCmd)
			t.Logf("tokens: %v", tokens)

			// Check bracket token is intact
			foundBracket := false
			for _, tok := range tokens {
				if strings.HasPrefix(tok, "[") {
					foundBracket = true
					t.Logf("bracket token: %q", tok)
					hasFindSpace := strings.Contains(tok, " find ")
					t.Logf("  HasPrefix([)=%v Contains(' find ')=%v", true, hasFindSpace)
				}
			}
			if !foundBracket {
				t.Errorf("no bracket token found in tokens %v", tokens)
			}

			endpoint, params, opts, err := translateRouterOSCommand(innerCmd)
			if err != nil {
				t.Fatalf("translateRouterOSCommand error: %v", err)
			}
			if endpoint != tt.wantEndpt {
				t.Errorf("endpoint=%q want %q", endpoint, tt.wantEndpt)
			}
			if opts.findMutation != tt.wantFindMut {
				t.Errorf("findMutation=%v want %v", opts.findMutation, tt.wantFindMut)
			}
			if len(opts.findFilters) != len(tt.wantFilters) {
				t.Errorf("findFilters=%v want %v", opts.findFilters, tt.wantFilters)
			} else {
				for i := range opts.findFilters {
					if opts.findFilters[i] != tt.wantFilters[i] {
						t.Errorf("findFilters[%d]=%q want %q", i, opts.findFilters[i], tt.wantFilters[i])
					}
				}
			}
			if len(params) != len(tt.wantParams) {
				t.Errorf("params=%v want %v", params, tt.wantParams)
			} else {
				for i := range params {
					if params[i] != tt.wantParams[i] {
						t.Errorf("params[%d]=%q want %q", i, params[i], tt.wantParams[i])
					}
				}
			}
		})
	}
}
